// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moderation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_moderation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_moderation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_moderation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_moderation_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_moderation_2eproto;
namespace moderation {
class ModerateObjectRequest;
struct ModerateObjectRequestDefaultTypeInternal;
extern ModerateObjectRequestDefaultTypeInternal _ModerateObjectRequest_default_instance_;
class ModerateObjectResponse;
struct ModerateObjectResponseDefaultTypeInternal;
extern ModerateObjectResponseDefaultTypeInternal _ModerateObjectResponse_default_instance_;
}  // namespace moderation
PROTOBUF_NAMESPACE_OPEN
template<> ::moderation::ModerateObjectRequest* Arena::CreateMaybeMessage<::moderation::ModerateObjectRequest>(Arena*);
template<> ::moderation::ModerateObjectResponse* Arena::CreateMaybeMessage<::moderation::ModerateObjectResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace moderation {

enum ObjectType : int {
  OBJECT_TYPE_UNSPECIFIED = 0,
  OBJECT_TYPE_MOD_DESCRIPTION = 1,
  OBJECT_TYPE_COMMENT_TEXT = 2,
  OBJECT_TYPE_USER_NAME = 3,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_UNSPECIFIED;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_USER_NAME;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
// ===================================================================

class ModerateObjectRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:moderation.ModerateObjectRequest) */ {
 public:
  inline ModerateObjectRequest() : ModerateObjectRequest(nullptr) {}
  ~ModerateObjectRequest() override;
  explicit PROTOBUF_CONSTEXPR ModerateObjectRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModerateObjectRequest(const ModerateObjectRequest& from);
  ModerateObjectRequest(ModerateObjectRequest&& from) noexcept
    : ModerateObjectRequest() {
    *this = ::std::move(from);
  }

  inline ModerateObjectRequest& operator=(const ModerateObjectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModerateObjectRequest& operator=(ModerateObjectRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModerateObjectRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModerateObjectRequest* internal_default_instance() {
    return reinterpret_cast<const ModerateObjectRequest*>(
               &_ModerateObjectRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ModerateObjectRequest& a, ModerateObjectRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ModerateObjectRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModerateObjectRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModerateObjectRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModerateObjectRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModerateObjectRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModerateObjectRequest& from) {
    ModerateObjectRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModerateObjectRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "moderation.ModerateObjectRequest";
  }
  protected:
  explicit ModerateObjectRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 3,
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string text = 3;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // .moderation.ObjectType type = 2;
  void clear_type();
  ::moderation::ObjectType type() const;
  void set_type(::moderation::ObjectType value);
  private:
  ::moderation::ObjectType _internal_type() const;
  void _internal_set_type(::moderation::ObjectType value);
  public:

  // @@protoc_insertion_point(class_scope:moderation.ModerateObjectRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    int64_t id_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_moderation_2eproto;
};
// -------------------------------------------------------------------

class ModerateObjectResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:moderation.ModerateObjectResponse) */ {
 public:
  inline ModerateObjectResponse() : ModerateObjectResponse(nullptr) {}
  ~ModerateObjectResponse() override;
  explicit PROTOBUF_CONSTEXPR ModerateObjectResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModerateObjectResponse(const ModerateObjectResponse& from);
  ModerateObjectResponse(ModerateObjectResponse&& from) noexcept
    : ModerateObjectResponse() {
    *this = ::std::move(from);
  }

  inline ModerateObjectResponse& operator=(const ModerateObjectResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModerateObjectResponse& operator=(ModerateObjectResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModerateObjectResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModerateObjectResponse* internal_default_instance() {
    return reinterpret_cast<const ModerateObjectResponse*>(
               &_ModerateObjectResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ModerateObjectResponse& a, ModerateObjectResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ModerateObjectResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModerateObjectResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModerateObjectResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModerateObjectResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModerateObjectResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModerateObjectResponse& from) {
    ModerateObjectResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModerateObjectResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "moderation.ModerateObjectResponse";
  }
  protected:
  explicit ModerateObjectResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:moderation.ModerateObjectResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_moderation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ModerateObjectRequest

// int64 id = 1;
inline void ModerateObjectRequest::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t ModerateObjectRequest::_internal_id() const {
  return _impl_.id_;
}
inline int64_t ModerateObjectRequest::id() const {
  // @@protoc_insertion_point(field_get:moderation.ModerateObjectRequest.id)
  return _internal_id();
}
inline void ModerateObjectRequest::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void ModerateObjectRequest::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:moderation.ModerateObjectRequest.id)
}

// .moderation.ObjectType type = 2;
inline void ModerateObjectRequest::clear_type() {
  _impl_.type_ = 0;
}
inline ::moderation::ObjectType ModerateObjectRequest::_internal_type() const {
  return static_cast< ::moderation::ObjectType >(_impl_.type_);
}
inline ::moderation::ObjectType ModerateObjectRequest::type() const {
  // @@protoc_insertion_point(field_get:moderation.ModerateObjectRequest.type)
  return _internal_type();
}
inline void ModerateObjectRequest::_internal_set_type(::moderation::ObjectType value) {
  
  _impl_.type_ = value;
}
inline void ModerateObjectRequest::set_type(::moderation::ObjectType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:moderation.ModerateObjectRequest.type)
}

// string text = 3;
inline void ModerateObjectRequest::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& ModerateObjectRequest::text() const {
  // @@protoc_insertion_point(field_get:moderation.ModerateObjectRequest.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ModerateObjectRequest::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:moderation.ModerateObjectRequest.text)
}
inline std::string* ModerateObjectRequest::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:moderation.ModerateObjectRequest.text)
  return _s;
}
inline const std::string& ModerateObjectRequest::_internal_text() const {
  return _impl_.text_.Get();
}
inline void ModerateObjectRequest::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* ModerateObjectRequest::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* ModerateObjectRequest::release_text() {
  // @@protoc_insertion_point(field_release:moderation.ModerateObjectRequest.text)
  return _impl_.text_.Release();
}
inline void ModerateObjectRequest::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:moderation.ModerateObjectRequest.text)
}

// -------------------------------------------------------------------

// ModerateObjectResponse

// bool success = 1;
inline void ModerateObjectResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ModerateObjectResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ModerateObjectResponse::success() const {
  // @@protoc_insertion_point(field_get:moderation.ModerateObjectResponse.success)
  return _internal_success();
}
inline void ModerateObjectResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ModerateObjectResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:moderation.ModerateObjectResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace moderation

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::moderation::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::moderation::ObjectType>() {
  return ::moderation::ObjectType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_moderation_2eproto
