// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: moderation.proto

#include "moderation.pb.h"
#include "moderation.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace moderation {

static const char* ModerationService_method_names[] = {
  "/moderation.ModerationService/ModerateObject",
};

std::unique_ptr< ModerationService::Stub> ModerationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModerationService::Stub> stub(new ModerationService::Stub(channel, options));
  return stub;
}

ModerationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ModerateObject_(ModerationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ModerationService::Stub::ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::moderation::ModerateObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ModerateObject_, context, request, response);
}

void ModerationService::Stub::async::ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModerateObject_, context, request, response, std::move(f));
}

void ModerationService::Stub::async::ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModerateObject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>* ModerationService::Stub::PrepareAsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::moderation::ModerateObjectResponse, ::moderation::ModerateObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ModerateObject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>* ModerationService::Stub::AsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncModerateObjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

ModerationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModerationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ModerationService::Service, ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ModerationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::moderation::ModerateObjectRequest* req,
             ::moderation::ModerateObjectResponse* resp) {
               return service->ModerateObject(ctx, req, resp);
             }, this)));
}

ModerationService::Service::~Service() {
}

::grpc::Status ModerationService::Service::ModerateObject(::grpc::ServerContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace moderation

