// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: moderation.proto
#ifndef GRPC_moderation_2eproto__INCLUDED
#define GRPC_moderation_2eproto__INCLUDED

#include "moderation.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace moderation {

class ModerationService final {
 public:
  static constexpr char const* service_full_name() {
    return "moderation.ModerationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::moderation::ModerateObjectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>> AsyncModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>>(AsyncModerateObjectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>> PrepareAsyncModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>>(PrepareAsyncModerateObjectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>* AsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::moderation::ModerateObjectResponse>* PrepareAsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::moderation::ModerateObjectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>> AsyncModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>>(AsyncModerateObjectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>> PrepareAsyncModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>>(PrepareAsyncModerateObjectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, std::function<void(::grpc::Status)>) override;
      void ModerateObject(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>* AsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::moderation::ModerateObjectResponse>* PrepareAsyncModerateObjectRaw(::grpc::ClientContext* context, const ::moderation::ModerateObjectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ModerateObject_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ModerateObject(::grpc::ServerContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ModerateObject() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestModerateObject(::grpc::ServerContext* context, ::moderation::ModerateObjectRequest* request, ::grpc::ServerAsyncResponseWriter< ::moderation::ModerateObjectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ModerateObject<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ModerateObject() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::moderation::ModerateObjectRequest* request, ::moderation::ModerateObjectResponse* response) { return this->ModerateObject(context, request, response); }));}
    void SetMessageAllocatorFor_ModerateObject(
        ::grpc::MessageAllocator< ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ModerateObject(
      ::grpc::CallbackServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ModerateObject<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ModerateObject() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ModerateObject() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestModerateObject(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ModerateObject() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ModerateObject(context, request, response); }));
    }
    ~WithRawCallbackMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ModerateObject(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ModerateObject : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ModerateObject() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::moderation::ModerateObjectRequest, ::moderation::ModerateObjectResponse>* streamer) {
                       return this->StreamedModerateObject(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ModerateObject() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ModerateObject(::grpc::ServerContext* /*context*/, const ::moderation::ModerateObjectRequest* /*request*/, ::moderation::ModerateObjectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedModerateObject(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::moderation::ModerateObjectRequest,::moderation::ModerateObjectResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ModerateObject<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ModerateObject<Service > StreamedService;
};

}  // namespace moderation


#endif  // GRPC_moderation_2eproto__INCLUDED
